"""Plan de cuentas chileno estándar para PyME (base IFRS / uso tributario SII).

Formato de cada fila: (codigo, nombre, tipo, imputable, flags)
Los flags son opcionales: "aux" exige auxiliar (cliente/proveedor),
"banco" marca cuentas conciliables, "cc" exige centro de costo.
"""
from __future__ import annotations

from contaflow.models.base import TipoCuenta

A, P, K, G, L, O = (
    TipoCuenta.ACTIVO, TipoCuenta.PASIVO, TipoCuenta.PATRIMONIO,
    TipoCuenta.GANANCIA, TipoCuenta.PERDIDA, TipoCuenta.ORDEN,
)

PLAN_CUENTAS: list[tuple[str, str, TipoCuenta, bool, str]] = [
    # ---------------------------------------------------------------- ACTIVOS
    ("1", "ACTIVOS", A, False, ""),
    ("1.1", "ACTIVO CORRIENTE", A, False, ""),
    ("1.1.01", "Efectivo y Equivalentes al Efectivo", A, False, ""),
    ("1.1.01.001", "Caja", A, True, ""),
    ("1.1.01.002", "Caja Chica", A, True, ""),
    ("1.1.01.003", "Banco Cuenta Corriente", A, True, "banco"),
    ("1.1.01.004", "Banco Cuenta Vista", A, True, "banco"),
    ("1.1.01.005", "Depósitos a Plazo", A, True, ""),
    ("1.1.01.006", "Fondos Mutuos", A, True, ""),
    ("1.1.02", "Deudores Comerciales y Otras Cuentas por Cobrar", A, False, ""),
    ("1.1.02.001", "Clientes Nacionales", A, True, "aux"),
    ("1.1.02.002", "Documentos por Cobrar", A, True, "aux"),
    ("1.1.02.003", "Cheques en Cartera", A, True, ""),
    ("1.1.02.004", "Deudores Varios", A, True, "aux"),
    ("1.1.02.005", "Estimación Deudores Incobrables", A, True, ""),
    ("1.1.03", "Cuentas por Cobrar a Relacionadas y Personal", A, False, ""),
    ("1.1.03.001", "Cuenta Particular Socios", A, True, "aux"),
    ("1.1.03.002", "Anticipo a Proveedores", A, True, "aux"),
    ("1.1.03.003", "Préstamos y Anticipos al Personal", A, True, "aux"),
    ("1.1.04", "Impuestos por Recuperar", A, False, ""),
    ("1.1.04.001", "IVA Crédito Fiscal", A, True, ""),
    ("1.1.04.002", "IVA Crédito Fiscal Activo Fijo", A, True, ""),
    ("1.1.04.003", "Remanente Crédito Fiscal", A, True, ""),
    ("1.1.04.004", "PPM por Recuperar", A, True, ""),
    ("1.1.04.005", "Crédito SENCE por Recuperar", A, True, ""),
    ("1.1.04.006", "Impuesto Renta por Recuperar", A, True, ""),
    ("1.1.04.007", "Retención Honorarios por Recuperar", A, True, ""),
    ("1.1.05", "Existencias", A, False, ""),
    ("1.1.05.001", "Mercaderías", A, True, ""),
    ("1.1.05.002", "Materias Primas", A, True, ""),
    ("1.1.05.003", "Productos en Proceso", A, True, ""),
    ("1.1.05.004", "Productos Terminados", A, True, ""),
    ("1.1.05.005", "Materiales y Suministros", A, True, ""),
    ("1.1.06", "Pagos Anticipados", A, False, ""),
    ("1.1.06.001", "Seguros Pagados por Anticipado", A, True, ""),
    ("1.1.06.002", "Arriendos Pagados por Anticipado", A, True, ""),
    ("1.1.06.003", "Otros Gastos Anticipados", A, True, ""),
    ("1.2", "ACTIVO NO CORRIENTE", A, False, ""),
    ("1.2.01", "Propiedades, Planta y Equipo", A, False, ""),
    ("1.2.01.001", "Terrenos", A, True, ""),
    ("1.2.01.002", "Construcciones y Obras de Infraestructura", A, True, ""),
    ("1.2.01.003", "Maquinarias y Equipos", A, True, ""),
    ("1.2.01.004", "Muebles y Útiles", A, True, ""),
    ("1.2.01.005", "Equipos Computacionales", A, True, ""),
    ("1.2.01.006", "Vehículos", A, True, ""),
    ("1.2.01.007", "Instalaciones", A, True, ""),
    ("1.2.01.008", "Herramientas", A, True, ""),
    ("1.2.02", "Depreciación Acumulada", A, False, ""),
    ("1.2.02.002", "Dep. Acumulada Construcciones", A, True, ""),
    ("1.2.02.003", "Dep. Acumulada Maquinarias y Equipos", A, True, ""),
    ("1.2.02.004", "Dep. Acumulada Muebles y Útiles", A, True, ""),
    ("1.2.02.005", "Dep. Acumulada Equipos Computacionales", A, True, ""),
    ("1.2.02.006", "Dep. Acumulada Vehículos", A, True, ""),
    ("1.2.02.007", "Dep. Acumulada Instalaciones", A, True, ""),
    ("1.2.03", "Activos Intangibles", A, False, ""),
    ("1.2.03.001", "Software y Licencias", A, True, ""),
    ("1.2.03.002", "Derechos de Marca y Patentes", A, True, ""),
    ("1.2.03.003", "Amortización Acumulada Intangibles", A, True, ""),
    ("1.2.04", "Inversiones y Otros Activos", A, False, ""),
    ("1.2.04.001", "Inversiones en Empresas Relacionadas", A, True, ""),
    ("1.2.04.002", "Activos por Impuestos Diferidos", A, True, ""),
    ("1.2.04.003", "Garantías y Depósitos en Garantía", A, True, ""),

    # ---------------------------------------------------------------- PASIVOS
    ("2", "PASIVOS", P, False, ""),
    ("2.1", "PASIVO CORRIENTE", P, False, ""),
    ("2.1.01", "Obligaciones Financieras Corto Plazo", P, False, ""),
    ("2.1.01.001", "Préstamos Bancarios Corto Plazo", P, True, ""),
    ("2.1.01.002", "Línea de Crédito", P, True, ""),
    ("2.1.01.003", "Obligaciones por Leasing Corto Plazo", P, True, ""),
    ("2.1.01.004", "Intereses por Pagar", P, True, ""),
    ("2.1.02", "Acreedores Comerciales y Otras Cuentas por Pagar", P, False, ""),
    ("2.1.02.001", "Proveedores Nacionales", P, True, "aux"),
    ("2.1.02.002", "Documentos por Pagar", P, True, "aux"),
    ("2.1.02.003", "Acreedores Varios", P, True, "aux"),
    ("2.1.02.004", "Anticipos de Clientes", P, True, "aux"),
    ("2.1.02.005", "Honorarios por Pagar", P, True, "aux"),
    ("2.1.03", "Impuestos por Pagar", P, False, ""),
    ("2.1.03.001", "IVA Débito Fiscal", P, True, ""),
    ("2.1.03.002", "IVA por Pagar", P, True, ""),
    ("2.1.03.003", "PPM por Pagar", P, True, ""),
    ("2.1.03.004", "Retención Honorarios 2ª Categoría", P, True, ""),
    ("2.1.03.005", "Impuesto Único a los Trabajadores", P, True, ""),
    ("2.1.03.006", "Impuesto a la Renta por Pagar", P, True, ""),
    ("2.1.03.007", "Impuestos Adicionales por Pagar (ILA)", P, True, ""),
    ("2.1.03.008", "Retención Cambio de Sujeto", P, True, ""),
    ("2.1.04", "Obligaciones Previsionales y con el Personal", P, False, ""),
    ("2.1.04.001", "Sueldos por Pagar", P, True, ""),
    ("2.1.04.002", "AFP por Pagar", P, True, ""),
    ("2.1.04.003", "Salud por Pagar (Fonasa / Isapre)", P, True, ""),
    ("2.1.04.004", "Seguro de Cesantía por Pagar", P, True, ""),
    ("2.1.04.005", "Mutual de Seguridad por Pagar", P, True, ""),
    ("2.1.04.006", "Caja de Compensación por Pagar", P, True, ""),
    ("2.1.04.007", "Provisión de Vacaciones", P, True, ""),
    ("2.1.04.008", "Provisión Indemnización Años de Servicio", P, True, ""),
    ("2.1.05", "Provisiones y Otros Pasivos", P, False, ""),
    ("2.1.05.001", "Provisión de Gastos", P, True, ""),
    ("2.1.05.002", "Retenciones Judiciales", P, True, ""),
    ("2.1.05.003", "Ingresos Percibidos por Adelantado", P, True, ""),
    ("2.2", "PASIVO NO CORRIENTE", P, False, ""),
    ("2.2.01", "Obligaciones Largo Plazo", P, False, ""),
    ("2.2.01.001", "Préstamos Bancarios Largo Plazo", P, True, ""),
    ("2.2.01.002", "Obligaciones por Leasing Largo Plazo", P, True, ""),
    ("2.2.01.003", "Pasivos por Impuestos Diferidos", P, True, ""),

    # ------------------------------------------------------------- PATRIMONIO
    ("3", "PATRIMONIO", K, False, ""),
    ("3.1", "PATRIMONIO NETO", K, False, ""),
    ("3.1.01", "Capital", K, False, ""),
    ("3.1.01.001", "Capital Pagado", K, True, ""),
    ("3.1.01.002", "Capital Suscrito por Enterar", K, True, ""),
    ("3.1.01.003", "Revalorización del Capital Propio", K, True, ""),
    ("3.1.02", "Reservas", K, False, ""),
    ("3.1.02.001", "Reserva Legal", K, True, ""),
    ("3.1.02.002", "Otras Reservas", K, True, ""),
    ("3.1.03", "Resultados", K, False, ""),
    ("3.1.03.001", "Utilidades Acumuladas", K, True, ""),
    ("3.1.03.002", "Pérdidas Acumuladas", K, True, ""),
    ("3.1.03.003", "Resultado del Ejercicio", K, True, ""),
    ("3.1.03.004", "Retiros y Dividendos Provisorios", K, True, "aux"),

    # ------------------------------------------------------- RESULTADO GANANCIA
    ("4", "INGRESOS", G, False, ""),
    ("4.1", "INGRESOS DE EXPLOTACIÓN", G, False, ""),
    ("4.1.01", "Ingresos por Ventas", G, False, ""),
    ("4.1.01.001", "Ventas Afectas", G, True, "cc"),
    ("4.1.01.002", "Ventas Exentas", G, True, "cc"),
    ("4.1.01.003", "Ventas de Exportación", G, True, "cc"),
    ("4.1.01.004", "Prestación de Servicios", G, True, "cc"),
    ("4.1.01.005", "Descuentos y Devoluciones sobre Ventas", G, True, ""),
    ("4.2", "OTROS INGRESOS", G, False, ""),
    ("4.2.01", "Ingresos Fuera de Explotación", G, False, ""),
    ("4.2.01.001", "Intereses Ganados", G, True, ""),
    ("4.2.01.002", "Utilidad en Venta de Activo Fijo", G, True, ""),
    ("4.2.01.003", "Arriendos Percibidos", G, True, ""),
    ("4.2.01.004", "Diferencia de Cambio Positiva", G, True, ""),
    ("4.2.01.005", "Corrección Monetaria (Abono)", G, True, ""),
    ("4.2.01.006", "Otros Ingresos", G, True, ""),

    # -------------------------------------------------------- RESULTADO PÉRDIDA
    ("5", "COSTOS Y GASTOS", L, False, ""),
    ("5.1", "COSTOS DE EXPLOTACIÓN", L, False, ""),
    ("5.1.01", "Costo de Ventas", L, False, ""),
    ("5.1.01.001", "Costo de Ventas Mercaderías", L, True, "cc"),
    ("5.1.01.002", "Costo de Servicios", L, True, "cc"),
    ("5.1.01.003", "Mano de Obra Directa", L, True, "cc"),
    ("5.1.01.004", "Materiales Directos", L, True, "cc"),
    ("5.1.01.005", "Compras del Giro", L, True, "cc"),
    ("5.2", "GASTOS DE ADMINISTRACIÓN Y VENTAS", L, False, ""),
    ("5.2.01", "Gastos del Personal", L, False, ""),
    ("5.2.01.001", "Sueldos y Salarios", L, True, "cc"),
    ("5.2.01.002", "Gratificaciones", L, True, "cc"),
    ("5.2.01.003", "Horas Extraordinarias", L, True, "cc"),
    ("5.2.01.004", "Bonos y Aguinaldos", L, True, "cc"),
    ("5.2.01.005", "Leyes Sociales (Aporte Empleador)", L, True, "cc"),
    ("5.2.01.006", "Mutual de Seguridad", L, True, "cc"),
    ("5.2.01.007", "Indemnizaciones", L, True, "cc"),
    ("5.2.01.008", "Honorarios Profesionales", L, True, "cc"),
    ("5.2.01.009", "Colación y Movilización", L, True, "cc"),
    ("5.2.01.010", "Capacitación", L, True, "cc"),
    ("5.2.02", "Gastos Generales", L, False, ""),
    ("5.2.02.001", "Arriendos", L, True, "cc"),
    ("5.2.02.002", "Electricidad, Agua y Gas", L, True, "cc"),
    ("5.2.02.003", "Telefonía e Internet", L, True, "cc"),
    ("5.2.02.004", "Materiales de Oficina", L, True, "cc"),
    ("5.2.02.005", "Aseo y Seguridad", L, True, "cc"),
    ("5.2.02.006", "Mantención y Reparaciones", L, True, "cc"),
    ("5.2.02.007", "Combustibles y Lubricantes", L, True, "cc"),
    ("5.2.02.008", "Fletes y Transporte", L, True, "cc"),
    ("5.2.02.009", "Publicidad y Marketing", L, True, "cc"),
    ("5.2.02.010", "Seguros", L, True, "cc"),
    ("5.2.02.011", "Patentes y Derechos Municipales", L, True, "cc"),
    ("5.2.02.012", "Gastos Notariales y Legales", L, True, "cc"),
    ("5.2.02.013", "Software y Servicios Computacionales", L, True, "cc"),
    ("5.2.02.014", "Viáticos y Gastos de Viaje", L, True, "cc"),
    ("5.2.02.015", "Gastos Bancarios y Comisiones", L, True, "cc"),
    ("5.2.02.016", "Suscripciones y Membresías", L, True, "cc"),
    ("5.2.02.017", "Gastos Generales Varios", L, True, "cc"),
    ("5.2.03", "Depreciaciones, Amortizaciones y Castigos", L, False, ""),
    ("5.2.03.001", "Depreciación del Ejercicio", L, True, "cc"),
    ("5.2.03.002", "Amortización de Intangibles", L, True, "cc"),
    ("5.2.03.003", "Castigo de Deudores Incobrables", L, True, ""),
    ("5.3", "GASTOS FUERA DE EXPLOTACIÓN", L, False, ""),
    ("5.3.01", "Gastos No Operacionales", L, False, ""),
    ("5.3.01.001", "Intereses y Gastos Financieros", L, True, ""),
    ("5.3.01.002", "Pérdida en Venta de Activo Fijo", L, True, ""),
    ("5.3.01.003", "Diferencia de Cambio Negativa", L, True, ""),
    ("5.3.01.004", "Corrección Monetaria (Cargo)", L, True, ""),
    ("5.3.01.005", "Multas e Intereses Fiscales", L, True, ""),
    ("5.3.01.006", "Gastos Rechazados Art. 21 LIR", L, True, ""),
    ("5.3.01.007", "IVA No Recuperable", L, True, ""),
    ("5.4", "IMPUESTO A LA RENTA", L, False, ""),
    ("5.4.01", "Impuesto a la Renta", L, False, ""),
    ("5.4.01.001", "Impuesto Renta Primera Categoría", L, True, ""),

    # ------------------------------------------------------- CUENTAS DE ORDEN
    ("9", "CUENTAS DE ORDEN", O, False, ""),
    ("9.1", "CUENTAS DE ORDEN", O, False, ""),
    ("9.1.01", "Cuentas de Orden Deudoras y Acreedoras", O, False, ""),
    ("9.1.01.001", "Documentos en Garantía", O, True, ""),
    ("9.1.01.002", "Contrapartida Documentos en Garantía", O, True, ""),
]


#: Cuentas por defecto usadas por los asientos automáticos.
CUENTAS_DEFECTO: dict[str, tuple[str, str]] = {
    "cta_caja":                 ("1.1.01.001", "Caja"),
    "cta_banco":                ("1.1.01.003", "Banco cuenta corriente"),
    "cta_clientes":             ("1.1.02.001", "Clientes (ventas a crédito)"),
    "cta_iva_credito":          ("1.1.04.001", "IVA crédito fiscal"),
    "cta_iva_credito_af":       ("1.1.04.002", "IVA crédito fiscal activo fijo"),
    "cta_remanente":            ("1.1.04.003", "Remanente crédito fiscal"),
    "cta_ppm":                  ("1.1.04.004", "PPM por recuperar"),
    "cta_retencion_bte":        ("1.1.04.007", "Retención honorarios por recuperar (BTE emitidas)"),
    "cta_existencias":          ("1.1.05.001", "Mercaderías"),
    "cta_proveedores":          ("2.1.02.001", "Proveedores (compras a crédito)"),
    "cta_honorarios_pagar":     ("2.1.02.005", "Honorarios por pagar"),
    "cta_iva_debito":           ("2.1.03.001", "IVA débito fiscal"),
    "cta_iva_por_pagar":        ("2.1.03.002", "IVA por pagar"),
    "cta_ppm_pagar":            ("2.1.03.003", "PPM por pagar"),
    "cta_retencion_honorarios": ("2.1.03.004", "Retención honorarios 2ª categoría"),
    "cta_impuesto_unico":       ("2.1.03.005", "Impuesto único a los trabajadores"),
    "cta_impuesto_adicional":   ("2.1.03.007", "Impuestos adicionales (ILA)"),
    "cta_retencion_sujeto":     ("2.1.03.008", "Retención cambio de sujeto"),
    "cta_sueldos_pagar":        ("2.1.04.001", "Sueldos por pagar"),
    "cta_afp_pagar":            ("2.1.04.002", "AFP por pagar"),
    "cta_salud_pagar":          ("2.1.04.003", "Salud por pagar"),
    "cta_afc_pagar":            ("2.1.04.004", "Seguro de cesantía por pagar"),
    "cta_mutual_pagar":         ("2.1.04.005", "Mutual por pagar"),
    "cta_resultado":            ("3.1.03.003", "Resultado del ejercicio"),
    "cta_utilidades":           ("3.1.03.001", "Utilidades acumuladas"),
    "cta_ventas_afectas":       ("4.1.01.001", "Ventas afectas"),
    "cta_ventas_exentas":       ("4.1.01.002", "Ventas exentas"),
    "cta_ventas_exportacion":   ("4.1.01.003", "Ventas de exportación"),
    "cta_compras":              ("5.1.01.005", "Compras del giro"),
    "cta_sueldos_gasto":        ("5.2.01.001", "Sueldos y salarios"),
    "cta_gratificacion_gasto":  ("5.2.01.002", "Gratificaciones"),
    "cta_leyes_sociales":       ("5.2.01.005", "Leyes sociales (aporte empleador)"),
    "cta_mutual_gasto":         ("5.2.01.006", "Mutual de seguridad"),
    "cta_honorarios_gasto":     ("5.2.01.008", "Honorarios profesionales"),
    "cta_colacion_gasto":       ("5.2.01.009", "Colación y movilización"),
    "cta_gastos_generales":     ("5.2.02.017", "Gastos generales varios"),
    "cta_depreciacion_gasto":   ("5.2.03.001", "Depreciación del ejercicio"),
    "cta_depreciacion_acum":    ("1.2.02.004", "Depreciación acumulada (por defecto)"),
    "cta_activo_fijo":          ("1.2.01.004", "Activo fijo (por defecto)"),
    "cta_iva_no_recuperable":   ("5.3.01.007", "IVA no recuperable"),
    "cta_impuesto_renta":       ("5.4.01.001", "Impuesto renta primera categoría"),
}


#: Catálogo de tipos de documento tributario del SII.
#: (codigo, nombre, es_venta, es_compra, afecto_iva, signo, electronico)
TIPOS_DTE: list[tuple[int, str, bool, bool, bool, int, bool]] = [
    (30,  "Factura",                                  True,  True,  True,   1, False),
    (32,  "Factura de Venta Exenta",                   True,  True,  False,  1, False),
    (33,  "Factura Electrónica",                       True,  True,  True,   1, True),
    (34,  "Factura No Afecta o Exenta Electrónica",    True,  True,  False,  1, True),
    (35,  "Boleta",                                    True,  False, True,   1, False),
    (38,  "Boleta Exenta",                             True,  False, False,  1, False),
    (39,  "Boleta Electrónica",                        True,  False, True,   1, True),
    (41,  "Boleta Exenta Electrónica",                 True,  False, False,  1, True),
    (43,  "Liquidación Factura Electrónica",           True,  True,  True,   1, True),
    (45,  "Factura de Compra",                         False, True,  True,   1, False),
    (46,  "Factura de Compra Electrónica",             False, True,  True,   1, True),
    (48,  "Comprobante de Pago Electrónico",           True,  False, True,   1, True),
    (50,  "Guía de Despacho",                          True,  False, True,   1, False),
    (52,  "Guía de Despacho Electrónica",              True,  False, True,   1, True),
    (55,  "Nota de Débito",                            True,  True,  True,   1, False),
    (56,  "Nota de Débito Electrónica",                True,  True,  True,   1, True),
    (60,  "Nota de Crédito",                           True,  True,  True,  -1, False),
    (61,  "Nota de Crédito Electrónica",               True,  True,  True,  -1, True),
    (101, "Factura de Exportación",                    True,  False, False,  1, False),
    (110, "Factura de Exportación Electrónica",        True,  False, False,  1, True),
    (111, "Nota de Débito de Exportación Electrónica", True,  False, False,  1, True),
    (112, "Nota de Crédito de Exportación Electrónica", True, False, False, -1, True),
    (914, "Declaración de Ingreso (DIN Importación)",  False, True,  True,   1, False),
]
